# Docker Compose til CLIENT maskiner (waiter/kitchen)
# Denne fil bruges KUN på maskiner der skal køre waiter eller kitchen apps
# Database serveren kører på en anden maskine

version: "3.9"

services:
  # Eksempel: Waiter App (tilpas efter behov)
  waiter:
    build:
      context: .
      dockerfile: Dockerfile.waiter  # Skal laves i waiter repository
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vesuvius_user:vesuvius_password@[HOST_IP]:5432/vesuvius_db
      - API_BASE_URL=http://[HOST_IP]:3000
    ports:
      - "3002:3000"
    networks:
      - client-network

  # Eksempel: Kitchen App (tilpas efter behov) 
  kitchen:
    build:
      context: .
      dockerfile: Dockerfile.kitchen  # Skal laves i kitchen repository
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vesuvius_user:vesuvius_password@[HOST_IP]:5432/vesuvius_db
      - API_BASE_URL=http://[HOST_IP]:3000
    ports:
      - "3003:3000"
    networks:
      - client-network

networks:
  client-network:
    driver: bridge
