services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vesuvius
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: vesuvius
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vesuvius -d vesuvius"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
